Task/follower groups
TheResonator/resonators-server pull request #29
Opened 2020-08-24 17:15 UTC by sOfekS

Made stats filenames more meaningful to the users.
Also added option to download all the group's stats (all resonators) - needs to merge along with [Client PR](https://github.com/TheResonator/resonators-client/pull/22)

2020-08-25 14:42 UTC, TswusayonaTsamsiyu requested changes

2020-08-25 14:42 UTC, TswusayonaTsamsiyu commented on src/api/routes/stats.js
> +        convertStatsToCSV(stats).pipe(response);
This code is a duplicate of the above.
You should create a "downloadFile" helper (which receives content type, file content and file name).

2020-08-25 14:42 UTC, TswusayonaTsamsiyu commented on src/application/resonatorStats.js
> +            resonator: resonator.title,
Why not just add this to all the resonator stats (even the regular ones not in groups)?
It will remove the need for all of this extra logic, both here and in `convertStatsToCSV`, and also create a consistent CSV interface for all downloaded stats (and everybody loves consistent interfaces 😄 ).

2020-08-25 14:42 UTC, TswusayonaTsamsiyu commented on src/application/resonatorStats.js
> +    return allGroupStats.reduce((acc, stat) => ({
You could just perform this logic above when adding the resonators, and decrease runtime complexity.

2020-08-25 14:42 UTC, TswusayonaTsamsiyu commented on src/application/resonatorStats.js
>          const question = questions.find(_.matches({ id: answer.question_id }));
Now I notice that this is `O(m*n)` complexity. Maybe `getResonatorStats` could already return a single array of unified objects (instead of separate arrays of questions and answers) so that we could just get rid of this function?

2020-08-25 18:53 UTC, sOfekS commented on src/application/resonatorStats.js
>          const question = questions.find(_.matches({ id: answer.question_id }));
We can't break the API. the client uses it to display the graphs for the resonators, and it's just bad practice to completely change the API's output. I don't like it either

2020-08-27 20:12 UTC, TswusayonaTsamsiyu approved these changes

2020-08-27 21:15 UTC, merged