Feature/reorder resonator questions
TheResonator/resonators-server pull request #49
Opened 2020-10-30 03:50 UTC by raverside

2020-10-30 22:54 UTC, TswusayonaTsamsiyu requested changes
Mostly minor changes. Looks fine overall 😄

2020-10-30 22:54 UTC, TswusayonaTsamsiyu commented on src/api/routes/followers/normalizers.js
> +    return sentResonator.resonator.resonator_questions.map((question) => ({
The `sort` method also returns the sorted array, so you can chain it with the `map` and shorten the code.
Like `sentResonator.resonator.resonator_questions.sort( ... ).map( ... )`

2020-10-30 22:54 UTC, TswusayonaTsamsiyu commented on src/application/resonatorStats.js
> +        sortedAnswers.forEach((a) => { questions.find(q => q.id === a.question_id).order = a.order });
Isn't the order added in line 35 above?
Maybe the nested `map` isn't necessary?

Anyway, if you leave this, please put the function body in a new line. It's hard to read the way it is now.

2020-10-30 22:54 UTC, TswusayonaTsamsiyu commented on src/domain/entities/resonator.js
> +        question.order = order;
What happens if another question already has that order value?

2020-10-30 22:54 UTC, TswusayonaTsamsiyu commented on src/domain/entities/resonator.js
> +        question.id = uuid();
Why is this needed?

2020-10-30 23:19 UTC, raverside commented on src/domain/entities/resonator.js
> +        question.id = uuid();
If you're asking about the reorderQuestion() in general - it updates the order of an existing question (use case: Leader adds some criteria to the resonator, saves. Then comes back and reorders the questions)
if you're asking about reassigning id (line 90) - without it the record doesn't get updated and the changes are discarded. I'm not sure if there's a better way to make it update the record but I couldn't figure it out.

2020-10-30 23:21 UTC, raverside commented on src/domain/entities/resonator.js
> +        question.order = order;
It's not supposed to. All criteria are assigned a unique order value

2020-10-30 23:24 UTC, raverside commented on src/application/resonatorStats.js
> +        sortedAnswers.forEach((a) => { questions.find(q => q.id === a.question_id).order = a.order });
On line 35 the order is added to the [answers]. On 42 I assign to [questions]
function body on a new line - ok, makes sense.

2020-10-30 23:25 UTC, raverside commented on src/api/routes/followers/normalizers.js
> +    return sentResonator.resonator.resonator_questions.map((question) => ({
good catch, thanks, will do

2020-10-31 21:37 UTC, TswusayonaTsamsiyu reviewed
See my comment regarding something that looks like an error.
If it works then I approve

2020-10-31 21:37 UTC, TswusayonaTsamsiyu commented on src/application/resonators.js
> +    for (const [order, question_id] of criteria_order.entries()) {
Ummm shouldn't it be `Object.entries(criteria_order)`?
or does babel somehow make this work?

2020-10-31 21:41 UTC, raverside commented on src/application/resonators.js
> +    for (const [order, question_id] of criteria_order.entries()) {
it's actually not Object.entries() but [Array.prototype.entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/entries), and yeah, works fine for me

2020-10-31 22:26 UTC, merged